### ISSUE TITLE
BindTo object throws cannot call method getValue of undefined

### ISSUE THREAD

**Issue by AirBorne04** [rsamec/react-binding#6]
The Binder.bindTo method throws an error
`Cannot call method 'getValue' of undefined
(STDERR)     at PathParentBinding.Object.defineProperty.get [as value] react-binding\index
.js:309:37)`

Digging into the source i found `Binder.bindTo` to return a `PathParentBinding`, rather than an `PathObjectBinding` which is trying to access `this.parent.source` rather than `this.parent` to retrieve the value. Is there a particular reason for this behaviour? Shouldn't `Binder.bindTo` return a `PathParentBinding`?

**Comment by rsamec** [comment]
-  Binder.bindTo returns PathParentBinding.
-  Binder.bindToState returns PathObjectBinding.
  
  Look at this example from tests folder. Hope this helps.

``` js
 //when
        var data = {
            Data: {
                "Person": {
                    "FirstName": initValues.firstName,
                    "LastName": initValues.lastName,
                    "Contact": {
                        "Email": initValues.email
                    }
                }
            }
        };

        //exec
        var root = new BindTo.PathObjectBinding(data.Data);
        var person = new BindTo.PathParentBinding(root,"Person");
        var firstName = new BindTo.PathParentBinding(person,"FirstName");
        var lastName = new BindTo.PathParentBinding(person,"LastName");
        var email = new BindTo.PathParentBinding(person,"Contact.Email");

```

**Comment by AirBorne04** [comment]
ah ok i cannot really directly use the shorthand `function Binder.bindTo` but instead need to go like

```
var person = { "name": "abc", "age": 25 };

var boundPerson = new BindTo.PathObjectBinding(person);
var boundName = new BindTo.PathParentBinding(boundPerson, "name");
```

and than continue to use boundName, I was thinking I could do it like

```
var person = { "name": "abc", "age": 25 };
Binder.bindTo(person, "name");
```

but than i ran into the error above.

Is there a reason, that there is not a short hand and or fallback handling when someone is not passing a `ParentBinding` but the `ParentObject` itself?

**Comment by rsamec** [comment]
Use Binder.bindToState instead of Binder.bindTo.

You have to bind to state, to react component with some state data

``` js

export default class Form extends React.Component {
  constructor(props){
    super(props);
    this.state = {person: { "name": "abc", "age": 25 }};
  },
  render {
    return (
      <div>
        <input valueLink={Binder.bindToState(this,"person", "name")} />
        <div>name: {this.state.person.name}</div>
      </div>
    )}
});
```

Binder.bindTo requires the first parameter an object that implements IPathObjectBinding (eihter PathObjectBinding or PathParentBinding). Plain Javascript object is not possible - it does not have reference for component with state.

Binder.bindToState(this,"person", "name") is equal to Binder.bindTo(Binder.bindToState(this,"person"), "name");

Hope this helps.

**Comment by AirBorne04** [comment]
Ok got it,
thanks
